name:                hslox
version:             0.1.0.0
github:              "gusbicalho/crafting-interpreters-hs"
author:              "Gustavo Bicalho"
maintainer:          "gusbicalho@gmail.com"
copyright:           "2020 Gustavo Bicalho"

description:         Please see the README on GitHub at <https://github.com/gusbicalho/crafting-interpreters-hs#readme>

defaults:
  local: ../defaults.yaml

dependencies:
  - base >= 4.7 && < 5
  - containers
  - fused-effects
  - megaparsec
  - mtl
  - optparse-applicative
  - text

library:
  source-dirs: src

executables:
  hslox-exe:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hslox
  hslox-test-dev:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
    - hspec
    - QuickCheck

tests:
  hslox-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hslox
    - hspec
    - QuickCheck
